function build_fwp_hp_operation()
%BUILD_FWP_HP_OPERATION Build and verify the FWP-HP operation mechanism.
% Protection uses absolute physical values only. No derivative alarm exists.

repoRoot=getenv('GITHUB_WORKSPACE');
if isempty(repoRoot), repoRoot=fileparts(fileparts(mfilename('fullpath'))); end
logicDir=fullfile(repoRoot,'ecms_pump_logic');
outDir=fullfile(repoRoot,'outputs');
if ~isfolder(outDir), mkdir(outDir); end

cfg=readcell(fullfile(logicDir,'fwp_hp_settings_v1.csv'),'Delimiter',',');
getv=@(name) settingValue(cfg,name);
sampleMs=getv('LOGIC_SAMPLE_TIME_MS'); Ts=sampleMs/1000;
ratedRpm=getv('FWP_RATED_SPEED_RPM');
speedProvenRpm=getv('SPEED_PROVEN_RPM'); zeroSpeedRpm=getv('ZERO_SPEED_RPM');
busMinKv=getv('BUS_START_MIN_KV');
breakerOpenN=round(getv('FWP_FEEDER_OPEN_DELAY_MS')/sampleMs);
accelTau=getv('MOTOR_ACCEL_TAU_S'); coastTau=getv('MOTOR_COAST_TAU_S');

modelName='TripLens_ECMS_FWP_HP_Operation_Core';
modelPath=fullfile(outDir,[modelName '.slx']);
if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelPath), delete(modelPath); end
new_system(modelName);
set_param(modelName,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep',num2str(Ts,'%.12g'),'StopTime','30', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Dataset', ...
    'Description',['FWP-HP operation core: normal-stop keeps VCB-A01 closed; ' ...
    'trip opens VCB-A01; RPM follows motor state dynamics. No derivative protection.']);

inputNames={'fwp_hp_run_request','fwp_hp_trip_request','fwp_hp_reset_request', ...
    'feeder_cb_reclose_cmd','remote_mode','feeder_cb_ready','motor_ready', ...
    'process_start_permissive','bus_a_voltage_kv','electrical_trip_active'};
inputTypes={'boolean','boolean','boolean','boolean','boolean','boolean', ...
    'boolean','boolean','double','boolean'};
for k=1:numel(inputNames)
    y=30+(k-1)*58;
    p=[modelName '/' inputNames{k}];
    add_block('simulink/Sources/In1',p,'Port',num2str(k), ...
        'Position',[20 y 210 y+22]);
    set_param(p,'OutDataTypeStr',inputTypes{k});
    c=[modelName '/in_double_' num2str(k)];
    add_block('simulink/Signal Attributes/Data Type Conversion',c, ...
        'OutDataTypeStr','double','Position',[235 y 285 y+22]);
    add_line(modelName,[inputNames{k} '/1'],['in_double_' num2str(k) '/1'],'autorouting','on');
end

controller='Operation_State_Machine';
controllerInputs={'runRequest','tripRequest','resetRequest','remoteMode', ...
    'cbReady','motorReady','processPermissive','busKv','electricalTrip','cbClosed','speedRpm'};
controllerOutputs={'runEnable','cbTrip','tripLatch','readyState','startingState', ...
    'runningState','stoppingState','trippedState','speedProven','stateCode'};
addLogicSubsystem(modelName,controller,controllerInputs,controllerOutputs, ...
    controllerCode(speedProvenRpm,zeroSpeedRpm,busMinKv),[350 45 665 520],[0.73 0.86 1]);

breaker='Feeder_Breaker_Actuator';
breakerInputs={'cbTrip','recloseRequest','tripLatch','cbReady','busKv','electricalTrip','speedRpm'};
addLogicSubsystem(modelName,breaker,breakerInputs,{'cbClosed'}, ...
    breakerCode(breakerOpenN,busMinKv,zeroSpeedRpm),[760 55 1035 285],[1 0.84 0.68]);
cbToDoubleName='CB_Feedback_As_Double';
cbToDouble=[modelName '/' cbToDoubleName];
add_block('simulink/Signal Attributes/Data Type Conversion',cbToDouble, ...
    'OutDataTypeStr','double','Position',[1060 185 1120 215]);

motor='Motor_Shaft_Dynamics';
addLogicSubsystem(modelName,motor,{'runEnable','cbClosed'},{'speedRpm','runFeedback'}, ...
    motorCode(Ts,ratedRpm,zeroSpeedRpm,accelTau,coastTau),[760 390 1035 530],[0.78 0.93 0.80]);

cbDelayName='CB_Feedback_Next_Sync';
cbDelay=[modelName '/' cbDelayName];
add_block('simulink/Discrete/Unit Delay',cbDelay,'SampleTime',num2str(Ts,'%.12g'), ...
    'InitialCondition','1','Position',[1160 110 1240 145]);
speedDelayName='Speed_Feedback_Next_Sync';
speedDelay=[modelName '/' speedDelayName];
add_block('simulink/Discrete/Unit Delay',speedDelay,'SampleTime',num2str(Ts,'%.12g'), ...
    'InitialCondition','0','Position',[1080 420 1160 455]);

% Root inputs to the state machine. Reclose is deliberately not a START input.
controllerRoot=[1 2 3 5 6 7 8 9 10];
for k=1:numel(controllerRoot)
    add_line(modelName,['in_double_' num2str(controllerRoot(k)) '/1'], ...
        [controller '/' num2str(k)],'autorouting','on');
end
add_line(modelName,[cbDelayName '/1'],[controller '/10'],'autorouting','on');
add_line(modelName,[speedDelayName '/1'],[controller '/11'],'autorouting','on');

% Controller -> breaker. The breaker receives a separate reclose request.
add_line(modelName,[controller '/2'],[breaker '/1'],'autorouting','on');
add_line(modelName,'in_double_4/1',[breaker '/2'],'autorouting','on');
add_line(modelName,[controller '/3'],[breaker '/3'],'autorouting','on');
add_line(modelName,'in_double_6/1',[breaker '/4'],'autorouting','on');
add_line(modelName,'in_double_9/1',[breaker '/5'],'autorouting','on');
add_line(modelName,'in_double_10/1',[breaker '/6'],'autorouting','on');
add_line(modelName,[speedDelayName '/1'],[breaker '/7'],'autorouting','on');
add_line(modelName,[breaker '/1'],[cbToDoubleName '/1'],'autorouting','on');
add_line(modelName,[cbToDoubleName '/1'],[cbDelayName '/1'],'autorouting','on');

% Controller/breaker -> motor and motor -> next synchronization point.
add_line(modelName,[controller '/1'],[motor '/1'],'autorouting','on');
add_line(modelName,[cbToDoubleName '/1'],[motor '/2'],'autorouting','on');
add_line(modelName,[motor '/1'],[speedDelayName '/1'],'autorouting','on');

outputNames={'run_enable_cmd','feeder_cb_trip_cmd','feeder_cb_closed_fb', ...
    'trip_latched','ready','starting','running','stopping','tripped','run_fb', ...
    'speed_rpm','speed_proven','state_code','thermo_speed_input_rpm'};
outputSources={[controller '/1'],[controller '/2'],[breaker '/1'],[controller '/3'], ...
    [controller '/4'],[controller '/5'],[controller '/6'],[controller '/7'], ...
    [controller '/8'],[motor '/2'],[motor '/1'],[controller '/9'], ...
    [controller '/10'],[motor '/1']};
for k=1:numel(outputNames)
    y=30+(k-1)*48;
    p=[modelName '/' outputNames{k}];
    add_block('simulink/Sinks/Out1',p,'Port',num2str(k), ...
        'Position',[1260 y 1475 y+22]);
    add_line(modelName,outputSources{k},[outputNames{k} '/1'],'autorouting','on');
end

set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelPath);

matlabDriveCopy='';
try
    mdrive=resolveMatlabDrive();
    if ~isempty(mdrive)
        targetDir=fullfile(mdrive,'TripLens_ECMS_DigitalTwin','models');
        if ~isfolder(targetDir), mkdir(targetDir); end
        matlabDriveCopy=fullfile(targetDir,[modelName '.slx']);
        copyfile(modelPath,matlabDriveCopy,'f');
    end
catch copyErr
    fprintf('MATLAB Drive copy skipped: %s\n',copyErr.message);
    matlabDriveCopy='';
end

% Deterministic virtual operation test. Inputs are stimuli, not plant records.
t=(0:Ts:30)'; N=numel(t);
runRequest=(t>=0.5 & t<6) | (t>=12 & t<20) | (t>=27);
tripRequest=t>=18 & t<18.2;
resetRequest=(t>=19 & t<19.05) | (t>=25 & t<25.05);
recloseRequest=t>=26 & t<26.05;
inputs={runRequest,tripRequest,resetRequest,recloseRequest,true(N,1), ...
    true(N,1),true(N,1),true(N,1),6.9*ones(N,1),false(N,1)};
ds=Simulink.SimulationData.Dataset;
for k=1:numel(inputNames)
    tsx=timeseries(inputs{k},t); tsx.Name=inputNames{k}; tsx=setinterpmethod(tsx,'zoh');
    ds=ds.addElement(tsx,inputNames{k});
end
simIn=Simulink.SimulationInput(modelName);
simIn=simIn.setExternalInput(ds);
simIn=simIn.setModelParameter('StopTime','30');
simOut=sim(simIn); yout=simOut.yout;

% Root Outport Dataset element names vary by MATLAB/Simulink release and
% localized installation.  The generated model's Outport numbers are the
% stable interface contract, so read the results by port order.
runEnable=signal(yout,1); cbTrip=signal(yout,2);
cbClosed=signal(yout,3); tripLatch=signal(yout,4);
ready=signal(yout,5); running=signal(yout,7); speed=signal(yout,11);
runFb=signal(yout,10); speedProven=signal(yout,12);

tripCmdTime=firstTrueTime(cbTrip,18);
cbOpenTime=firstFalseTime(cbClosed,18);
checks=struct();
checks.initial_ready_breaker_closed=logical(valueAt(ready,0.1)) && logical(valueAt(cbClosed,0.1));
checks.start_uses_preclosed_breaker=logical(valueAt(cbClosed,0.55)) && logical(valueAt(runEnable,0.55));
checks.start_reaches_run_feedback=logical(valueAt(runFb,0.7));
checks.start_reaches_absolute_speed_proven=logical(valueAt(speedProven,4.0)) && logical(valueAt(running,4.0));
checks.normal_stop_keeps_breaker_closed=all(logical(windowData(cbClosed,6,17.99)));
checks.normal_stop_does_not_zero_rpm_instantly=valueAt(speed,6.01)>zeroSpeedRpm;
checks.normal_stop_coastdown_monotonic=isNonIncreasing(windowData(speed,6,11.9),1e-7);
checks.normal_stop_returns_ready=logical(valueAt(ready,11.9));
checks.restart_before_trip=logical(valueAt(running,17));
checks.trip_command_latches=logical(valueAt(cbTrip,18.5)) && logical(valueAt(tripLatch,18.5));
checks.trip_opens_breaker_after_delay=abs((cbOpenTime-tripCmdTime)-getv('FWP_FEEDER_OPEN_DELAY_MS')/1000)<=2*Ts;
checks.trip_rpm_coasts_not_jumps=valueAt(speed,18.001)>zeroSpeedRpm && ...
    valueAt(speed,18.08)>zeroSpeedRpm && valueAt(speed,18.08)<valueAt(speed,17.999);
checks.invalid_reset_while_rotating_rejected=logical(valueAt(tripLatch,19.1));
checks.valid_reset_after_zero_speed_accepted=~logical(valueAt(tripLatch,25.1));
checks.reset_does_not_reclose_breaker=~logical(valueAt(cbClosed,25.5));
checks.separate_reclose_closes_breaker=logical(valueAt(cbClosed,26.1));
checks.no_automatic_restart_after_reclose=~logical(valueAt(runEnable,26.5));
checks.new_run_edge_restarts=logical(valueAt(runEnable,27.1));
pass=all(structfun(@(x)logical(x),checks));

sampleTimes=[0.1 0.5 0.7 4 6 6.01 11.9 12 17 18 18.08 19.1 25.1 25.5 26.1 26.5 27.1 30]';
timeline=table(sampleTimes, ...
    arrayfun(@(q)valueAt(runEnable,q),sampleTimes), ...
    arrayfun(@(q)valueAt(cbTrip,q),sampleTimes), ...
    arrayfun(@(q)valueAt(cbClosed,q),sampleTimes), ...
    arrayfun(@(q)valueAt(tripLatch,q),sampleTimes), ...
    arrayfun(@(q)valueAt(runFb,q),sampleTimes), ...
    arrayfun(@(q)valueAt(speed,q),sampleTimes), ...
    arrayfun(@(q)valueAt(ready,q),sampleTimes), ...
    arrayfun(@(q)valueAt(running,q),sampleTimes), ...
    'VariableNames',{'time_s','run_enable_cmd','feeder_cb_trip_cmd', ...
    'feeder_cb_closed_fb','trip_latched','run_fb','speed_rpm','ready','running'});
writetable(timeline,fullfile(outDir,'ecms_fwp_hp_operation_timeline.csv'),'Encoding','UTF-8');

pngPath=fullfile(outDir,'ecms_fwp_hp_operation_core.png');
pngGenerated=false; pngMessage='';
try
    open_system(modelName); set_param(modelName,'ZoomFactor','FitSystem');
    print(['-s' modelName],'-dpng','-r150',pngPath); pngGenerated=isfile(pngPath);
catch imageErr
    pngMessage=imageErr.message;
end

report=struct(); report.model=modelName; report.model_path=modelPath;
report.matlab_drive_copy=matlabDriveCopy; report.pass=pass; report.checks=checks;
report.sample_time_ms=sampleMs; report.rated_speed_rpm=ratedRpm;
report.speed_proven_rpm=speedProvenRpm; report.zero_speed_rpm=zeroSpeedRpm;
report.breaker_open_delay_ms=getv('FWP_FEEDER_OPEN_DELAY_MS');
report.actual_trip_command_time_s=tripCmdTime; report.actual_breaker_open_time_s=cbOpenTime;
report.normal_stop_breaker_state='CLOSED'; report.trip_breaker_state='OPEN_AFTER_DELAY';
report.no_auto_restart=true; report.start_does_not_close_breaker=true;
report.derivative_alarm_count=0; report.active_process_h_hh_l_ll_count=0;
report.png_generated=pngGenerated; report.png_message=pngMessage;
report.external_physics_binding='PENDING_COSIM_WIRING';
report.mechanism_note=['RPM is a virtual motor-shaft state driven by run enable and breaker state. ' ...
    'It is not forced from rated speed to zero at the trip timestamp.'];
report.setting_guardrail=['1400 rpm is source-model exact. Breaker timing and motor time constants ' ...
    'are virtual-model parameters and are not plant-approved settings.'];
fid=fopen(fullfile(outDir,'ecms_fwp_hp_operation_report.json'),'w','n','UTF-8');
assert(fid>=0,'TripLens:ReportWrite','Could not write FWP operation report.');
fprintf(fid,'%s',jsonencode(report,'PrettyPrint',true)); fclose(fid);
fprintf(['TRIPLENS FWP-HP OPERATION CORE BUILT\nPASS=%d\nTRIP_CMD=%.6f\n' ...
    'CB_OPEN=%.6f\nNORMAL_STOP_CB_CLOSED=%d\nNO_AUTO_RESTART=%d\n'], ...
    pass,tripCmdTime,cbOpenTime,checks.normal_stop_keeps_breaker_closed, ...
    checks.no_automatic_restart_after_reclose);
if ~pass, error('TripLens:FwpOperationTestFailed','FWP-HP operation test failed.'); end
close_system(modelName,0);
end

function value=settingValue(raw,name)
% Skip the header and use stable cell positions. This avoids localized
% readtable header/type normalization on the Windows self-hosted runner.
settingIds=strtrim(string(raw(2:end,1)));
settingValues=strtrim(string(raw(2:end,3)));
idx=find(settingIds==string(name),1);
if isempty(idx), error('TripLens:MissingSetting','Missing setting %s',name); end
value=str2double(settingValues(idx));
if isnan(value), error('TripLens:BadSetting','Non-numeric setting %s',name); end
end

function addLogicSubsystem(modelName,subName,inputNames,outputNames,code,position,color)
subPath=[modelName '/' subName];
add_block('simulink/Ports & Subsystems/Subsystem',subPath,'Position',position, ...
    'BackgroundColor',mat2str(color),'ForegroundColor','black','FontWeight','bold');
children=find_system(subPath,'SearchDepth',1,'Type','Block');
children=children(~strcmp(children,subPath));
lines=find_system(subPath,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines), delete_line(lines); end
for k=1:numel(children), delete_block(children{k}); end
for k=1:numel(inputNames)
    y=25+(k-1)*34;
    add_block('simulink/Sources/In1',[subPath '/' inputNames{k}], ...
        'Port',num2str(k),'Position',[20 y 150 y+20]);
end
logicPath=[subPath '/Logic'];
logicHeight=max(110,40+numel(inputNames)*30);
add_block('simulink/User-Defined Functions/MATLAB Function',logicPath, ...
    'Position',[205 40 470 logicHeight]);
rt=sfroot; chart=rt.find('-isa','Stateflow.EMChart','Path',logicPath);
if isempty(chart), error('TripLens:MATLABFunctionChart','Could not resolve %s.',logicPath); end
chart.Script=code;
for k=1:numel(outputNames)
    y=35+(k-1)*38;
    add_block('simulink/Sinks/Out1',[subPath '/' outputNames{k}], ...
        'Port',num2str(k),'Position',[530 y 690 y+20]);
end
set_param(modelName,'SimulationCommand','update');
for k=1:numel(inputNames)
    add_line(subPath,[inputNames{k} '/1'],['Logic/' num2str(k)],'autorouting','on');
end
for k=1:numel(outputNames)
    add_line(subPath,['Logic/' num2str(k)],[outputNames{k} '/1'],'autorouting','on');
end
set_param(subPath,'Description',sprintf('FWP-HP ECMS mechanism: %s',strrep(subName,'_',' ')));
end

function code=controllerCode(speedProvenRpm,zeroSpeedRpm,busMinKv)
lines={ ...
'function [runEnable,cbTrip,tripLatchOut,ready,starting,running,stopping,tripped,speedProven,stateCode] = Logic(runRequest,tripRequest,resetRequest,remoteMode,cbReady,motorReady,processPermissive,busKv,electricalTrip,cbClosed,speedRpm)' ...
'persistent state runLatch tripLatch previousRun' ...
'if isempty(state)' ...
'    state = 1;' ...
'    runLatch = false;' ...
'    tripLatch = false;' ...
'    previousRun = false;' ...
'end' ...
sprintf('SPEED_PROVEN_RPM = %.17g;',speedProvenRpm) ...
sprintf('ZERO_SPEED_RPM = %.17g;',zeroSpeedRpm) ...
sprintf('BUS_MIN_KV = %.17g;',busMinKv) ...
'runRequest = runRequest > 0.5;' ...
'tripRequest = tripRequest > 0.5;' ...
'resetRequest = resetRequest > 0.5;' ...
'remoteMode = remoteMode > 0.5;' ...
'cbReady = cbReady > 0.5;' ...
'motorReady = motorReady > 0.5;' ...
'processPermissive = processPermissive > 0.5;' ...
'electricalTrip = electricalTrip > 0.5;' ...
'cbClosed = cbClosed > 0.5;' ...
'startEdge = runRequest && ~previousRun;' ...
'stopEdge = ~runRequest && previousRun;' ...
'previousRun = runRequest;' ...
'speedProven = speedRpm >= SPEED_PROVEN_RPM;' ...
'zeroSpeed = speedRpm <= ZERO_SPEED_RPM;' ...
'tripCause = tripRequest || electricalTrip;' ...
'startPermissive = remoteMode && cbReady && motorReady && processPermissive && cbClosed && (busKv >= BUS_MIN_KV) && ~tripLatch && zeroSpeed;' ...
'if tripCause' ...
'    tripLatch = true;' ...
'    runLatch = false;' ...
'    state = 5;' ...
'elseif tripLatch' ...
'    runLatch = false;' ...
'    state = 5;' ...
'    if resetRequest && ~runRequest && zeroSpeed && ~cbClosed' ...
'        tripLatch = false;' ...
'        state = 6;' ...
'    end' ...
'else' ...
'    if state == 1' ...
'        runLatch = false;' ...
'        if startEdge && startPermissive' ...
'            runLatch = true;' ...
'            state = 2;' ...
'        end' ...
'    elseif state == 2' ...
'        if stopEdge || ~runRequest' ...
'            runLatch = false;' ...
'            state = 4;' ...
'        elseif speedProven' ...
'            state = 3;' ...
'        end' ...
'    elseif state == 3' ...
'        if stopEdge || ~runRequest' ...
'            runLatch = false;' ...
'            state = 4;' ...
'        end' ...
'    elseif state == 4' ...
'        runLatch = false;' ...
'        if zeroSpeed && cbClosed' ...
'            state = 1;' ...
'        end' ...
'    elseif state == 6' ...
'        runLatch = false;' ...
'        if cbClosed && zeroSpeed' ...
'            state = 1;' ...
'        end' ...
'    else' ...
'        runLatch = false;' ...
'        state = 1;' ...
'    end' ...
'end' ...
'runEnable = runLatch;' ...
'cbTrip = tripLatch;' ...
'tripLatchOut = tripLatch;' ...
'ready = state == 1;' ...
'starting = state == 2;' ...
'running = state == 3;' ...
'stopping = state == 4;' ...
'tripped = state == 5;' ...
'stateCode = state;' ...
'end'};
code=strjoin(lines,newline);
end

function code=breakerCode(openN,busMinKv,zeroSpeedRpm)
lines={ ...
'function cbClosedOut = Logic(cbTrip,recloseRequest,tripLatch,cbReady,busKv,electricalTrip,speedRpm)' ...
'persistent cbClosed openCount' ...
'if isempty(cbClosed)' ...
'    cbClosed = true;' ...
'    openCount = 0;' ...
'end' ...
sprintf('OPEN_N = %.17g;',openN) ...
sprintf('BUS_MIN_KV = %.17g;',busMinKv) ...
sprintf('ZERO_SPEED_RPM = %.17g;',zeroSpeedRpm) ...
'cbTrip = cbTrip > 0.5;' ...
'recloseRequest = recloseRequest > 0.5;' ...
'tripLatch = tripLatch > 0.5;' ...
'cbReady = cbReady > 0.5;' ...
'electricalTrip = electricalTrip > 0.5;' ...
'if (cbTrip || tripLatch || electricalTrip) && cbClosed' ...
'    openCount = openCount + 1;' ...
'    if openCount > OPEN_N' ...
'        cbClosed = false;' ...
'    end' ...
'elseif ~(cbTrip || tripLatch || electricalTrip)' ...
'    openCount = 0;' ...
'    if recloseRequest && cbReady && (busKv >= BUS_MIN_KV) && (speedRpm <= ZERO_SPEED_RPM)' ...
'        cbClosed = true;' ...
'    end' ...
'end' ...
'cbClosedOut = cbClosed;' ...
'end'};
code=strjoin(lines,newline);
end

function code=motorCode(Ts,ratedRpm,zeroSpeedRpm,accelTau,coastTau)
lines={ ...
'function [speedRpm,runFeedback] = Logic(runEnable,cbClosed)' ...
'persistent speed energized' ...
'if isempty(speed)' ...
'    speed = 0;' ...
'    energized = false;' ...
'end' ...
sprintf('TS = %.17g;',Ts) ...
sprintf('RATED_RPM = %.17g;',ratedRpm) ...
sprintf('ZERO_SPEED_RPM = %.17g;',zeroSpeedRpm) ...
sprintf('ACCEL_TAU_S = %.17g;',accelTau) ...
sprintf('COAST_TAU_S = %.17g;',coastTau) ...
'runEnable = runEnable > 0.5;' ...
'cbClosed = cbClosed > 0.5;' ...
'runFeedback = energized;' ...
'if energized' ...
'    alpha = min(1,TS/ACCEL_TAU_S);' ...
'    speed = speed + alpha*(RATED_RPM-speed);' ...
'else' ...
'    alpha = min(1,TS/COAST_TAU_S);' ...
'    speed = speed + alpha*(0-speed);' ...
'    if speed <= ZERO_SPEED_RPM' ...
'        speed = 0;' ...
'    end' ...
'end' ...
'if speed < 0' ...
'    speed = 0;' ...
'elseif speed > RATED_RPM' ...
'    speed = RATED_RPM;' ...
'end' ...
'energized = runEnable && cbClosed;' ...
'speedRpm = speed;' ...
'end'};
code=strjoin(lines,newline);
end

function ts=signal(yout,index)
element=yout.getElement(index);
if isa(element,'Simulink.SimulationData.Signal')
    ts=element.Values;
elseif isa(element,'timeseries')
    ts=element;
else
    error('TripLens:UnexpectedOutputType', ...
        'Unexpected output element type at Outport %d: %s',index,class(element));
end
end
function value=valueAt(ts,q)
[~,idx]=min(abs(ts.Time-q)); value=double(ts.Data(idx));
end
function data=windowData(ts,a,b)
mask=ts.Time>=a & ts.Time<=b; data=double(ts.Data(mask));
end
function ok=isNonIncreasing(data,tol)
ok=~isempty(data) && all(diff(data)<=tol);
end
function value=firstTrueTime(ts,after)
idx=find(ts.Time>=after & logical(ts.Data),1,'first');
if isempty(idx), value=NaN; else, value=double(ts.Time(idx)); end
end
function value=firstFalseTime(ts,after)
idx=find(ts.Time>=after & ~logical(ts.Data),1,'first');
if isempty(idx), value=NaN; else, value=double(ts.Time(idx)); end
end
function mdrive=resolveMatlabDrive()
mdrive='';
try
    if exist('matlabdrive','file')==2, mdrive=matlabdrive; end
catch
end
if isempty(mdrive)
    candidate=fullfile(getenv('USERPROFILE'),'MATLAB Drive');
    if isfolder(candidate), mdrive=candidate; end
end
end
