function build_a_logic_core()
%BUILD_A_LOGIC_CORE Generate/validate A-program -> ECMS Simulink logic core.
% Physical quantities are external inputs. No V/I/f/power is synthesized here.

repoRoot = getenv('GITHUB_WORKSPACE');
if isempty(repoRoot)
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
end
logicDir = fullfile(repoRoot,'ecms_logic');
outDir = fullfile(repoRoot,'outputs');
if ~isfolder(outDir), mkdir(outDir); end

cfg = readtable(fullfile(logicDir,'a_logic_settings_v1.csv'), ...
    'TextType','string','VariableNamingRule','preserve');
getv = @(name) settingValue(cfg,name);
sampleMs = getv('LOGIC_SAMPLE_TIME_MS');
Ts = sampleMs/1000;
recvN = round(getv('TRIP_RECEIVE_DELAY_MS')/sampleMs);
lockN = round((getv('TRIP_RECEIVE_DELAY_MS')+getv('LOCKOUT_OPERATE_DELAY_MS'))/sampleMs);
breakerN = round(getv('GT_BREAKER_OPEN_DELAY_MS')/sampleMs);
uvN = round(getv('UNDERVOLTAGE_DELAY_MS')/sampleMs);
uvPickupKv = getv('BUS_UNDERVOLTAGE_PICKUP_KV');
stLowMw = getv('ST_LOW_POWER_MW');

modelName = 'TripLens_ECMS_A_Logic_Core';
modelPath = fullfile(outDir,[modelName '.slx']);
if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelPath), delete(modelPath); end
new_system(modelName);
set_param(modelName,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep',num2str(Ts,'%.12g'),'StopTime','1.2', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Dataset', ...
    'Description',['TripLens A-program logic migration core v2. Absolute engineering-unit Tag Master bound. ' ...
    'Physical states are supplied by Electrical/Thermo twins.']);

inputNames = {'gt_trip_cmd','relay_86gt_healthy','cb_52gt_reset_cmd', ...
    'cb_52gt_closed_fb','bus_a_voltage_kv','bus_b_voltage_kv', ...
    'bus_a_native_live','bus_b_native_live','bus_a_fault_active', ...
    'bus_b_fault_active','stg_power_mw','auto_bus_tie_enable', ...
    'allow_source_parallel'};
inputTypes = {'boolean','boolean','boolean','boolean','double','double', ...
    'boolean','boolean','boolean','boolean','double','boolean','boolean'};
outputNames = {'relay_86gt_trip_received','relay_86gt_operated', ...
    'cb_52gt_trip_cmd','bus_a_27uv_operate','bus_b_27uv_operate', ...
    'cb_tie_ab_auto_close_permissive','stg_low_state'};

muxPath = [modelName '/Input_Vector'];
add_block('simulink/Signal Routing/Mux',muxPath,'Inputs',num2str(numel(inputNames)), ...
    'Position',[270 85 275 555]);
for k = 1:numel(inputNames)
    y = 35+(k-1)*42;
    inPath = [modelName '/' inputNames{k}];
    add_block('simulink/Sources/In1',inPath,'Position',[25 y 155 y+22],'Port',num2str(k));
    set_param(inPath,'OutDataTypeStr',inputTypes{k});
    cvtPath = [modelName '/to_double_' num2str(k)];
    add_block('simulink/Signal Attributes/Data Type Conversion',cvtPath, ...
        'OutDataTypeStr','double','Position',[180 y 225 y+22]);
    add_line(modelName,[inputNames{k} '/1'],['to_double_' num2str(k) '/1'],'autorouting','on');
    add_line(modelName,['to_double_' num2str(k) '/1'],['Input_Vector/' num2str(k)],'autorouting','on');
end

mfPath = [modelName '/A_Logic_State'];
add_block('simulink/User-Defined Functions/MATLAB Function',mfPath, ...
    'Position',[350 175 645 405]);
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',mfPath);
if isempty(chart), error('TripLens:MATLABFunctionChart','Could not resolve MATLAB Function chart.'); end
chart.Script = buildFunctionCode(recvN,lockN,breakerN,uvN,uvPickupKv,stLowMw);

outDemux = [modelName '/Output_Vector'];
add_block('simulink/Signal Routing/Demux',outDemux,'Outputs',num2str(numel(outputNames)), ...
    'Position',[710 160 715 440]);
add_line(modelName,'Input_Vector/1','A_Logic_State/1','autorouting','on');
add_line(modelName,'A_Logic_State/1','Output_Vector/1','autorouting','on');
for k = 1:numel(outputNames)
    y = 110+(k-1)*58;
    cvtPath = [modelName '/to_bool_' num2str(k)];
    add_block('simulink/Signal Attributes/Data Type Conversion',cvtPath, ...
        'OutDataTypeStr','boolean','Position',[755 y 805 y+22]);
    outPath = [modelName '/' outputNames{k}];
    add_block('simulink/Sinks/Out1',outPath,'Position',[850 y 1025 y+22],'Port',num2str(k));
    add_line(modelName,['Output_Vector/' num2str(k)],['to_bool_' num2str(k) '/1'],'autorouting','on');
    add_line(modelName,['to_bool_' num2str(k) '/1'],[outputNames{k} '/1'],'autorouting','on');
end
set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelPath);

matlabDriveCopy = '';
try
    mdrive = '';
    if exist('matlabdrive','file') == 2, mdrive = matlabdrive; end
    if isempty(mdrive)
        candidate = fullfile(getenv('USERPROFILE'),'MATLAB Drive');
        if isfolder(candidate), mdrive = candidate; end
    end
    if ~isempty(mdrive) && isfolder(mdrive)
        targetDir = fullfile(mdrive,'TripLens_ECMS_DigitalTwin','models');
        if ~isfolder(targetDir), mkdir(targetDir); end
        matlabDriveCopy = fullfile(targetDir,[modelName '.slx']);
        copyfile(modelPath,matlabDriveCopy,'f');
    end
catch copyErr
    fprintf('MATLAB Drive copy skipped: %s\n',copyErr.message);
    matlabDriveCopy = '';
end

% Standalone smoke inputs. These are test stimuli only, not plant physics.
t = (0:Ts:1.2)'; N = numel(t);
inputs = cell(1,numel(inputNames));
inputs{1}=t>=0.500; inputs{2}=true(N,1); inputs{3}=false(N,1); inputs{4}=true(N,1);
inputs{5}=6.9*ones(N,1); inputs{5}(t>=0.700)=3.45;
inputs{6}=6.9*ones(N,1);
inputs{7}=true(N,1); inputs{7}(t>=0.700)=false;
inputs{8}=true(N,1); inputs{9}=false(N,1); inputs{10}=false(N,1);
inputs{11}=277*ones(N,1); inputs{12}=false(N,1); inputs{13}=false(N,1);

ds = Simulink.SimulationData.Dataset;
for k=1:numel(inputNames)
    tsx = timeseries(inputs{k},t); tsx.Name=inputNames{k}; tsx=setinterpmethod(tsx,'zoh');
    ds = ds.addElement(tsx,inputNames{k});
end
simIn = Simulink.SimulationInput(modelName);
simIn = simIn.setExternalInput(ds);
simIn = simIn.setModelParameter('StopTime','1.2');
simOut = sim(simIn); yout = simOut.yout;
actualReceive=firstTrueTime(yout,1); actualLockout=firstTrueTime(yout,2);
actualBreaker=firstTrueTime(yout,3); actualUvA=firstTrueTime(yout,4);
tieSig=yout.getElement(6).Values; stLowSig=yout.getElement(7).Values;
expectedReceive=0.500+getv('TRIP_RECEIVE_DELAY_MS')/1000;
expectedLockout=0.500+(getv('TRIP_RECEIVE_DELAY_MS')+getv('LOCKOUT_OPERATE_DELAY_MS'))/1000;
expectedBreaker=0.500+getv('GT_BREAKER_OPEN_DELAY_MS')/1000;
expectedUvA=0.700+getv('UNDERVOLTAGE_DELAY_MS')/1000;
tol=Ts+1e-9;
checks=struct();
checks.gt_trip_receive=abs(actualReceive-expectedReceive)<=tol;
checks.gt_86_lockout=abs(actualLockout-expectedLockout)<=tol;
checks.gt_52_trip=abs(actualBreaker-expectedBreaker)<=tol;
checks.bus_a_27uv=abs(actualUvA-expectedUvA)<=tol;
checks.tie_disabled_default=~any(logical(tieSig.Data));
checks.st_low_not_fabricated=~any(logical(stLowSig.Data));
pass=all(structfun(@(x) logical(x),checks));

report=struct(); report.model=modelName; report.model_path=modelPath;
report.matlab_drive_copy=matlabDriveCopy; report.tag_master_binding='ABSOLUTE_LOGIC_MASTER_V2';
report.logic_sample_time_ms=sampleMs; report.source_logic='A program reference implementation';
report.migrated_v1=outputNames;
report.physical_inputs_not_synthesized={'bus_a_voltage_kv','bus_b_voltage_kv', ...
    'cb_52gt_closed_fb','bus_a_native_live','bus_b_native_live','stg_power_mw'};
report.expected_times_s=struct('trip_receive',expectedReceive,'lockout',expectedLockout, ...
    'breaker_trip',expectedBreaker,'bus_a_uv',expectedUvA);
report.actual_times_s=struct('trip_receive',actualReceive,'lockout',actualLockout, ...
    'breaker_trip',actualBreaker,'bus_a_uv',actualUvA);
report.checks=checks; report.pass=pass;
report.note=['V2 uses absolute kV and MW inputs. Settings are virtual-model calibrated and not plant approved. ' ...
    'Final tag binding, 50/51 physics, approved reset permissives and motor protection remain deferred.'];
reportPath=fullfile(outDir,'ecms_a_logic_core_report.json');
fid=fopen(reportPath,'w','n','UTF-8');
if fid<0, error('TripLens:ReportWrite','Could not write logic report.'); end
fprintf(fid,'%s',jsonencode(report,'PrettyPrint',true)); fclose(fid);
fprintf('TRIPLENS A->ECMS LOGIC CORE BUILT\nMODEL=%s\nPASS=%d\n',modelPath,pass);
if ~pass, error('TripLens:ALogicSmokeFailed','A-program ECMS logic smoke test failed.'); end
close_system(modelName,0);
end

function value=settingValue(tbl,name)
idx=find(tbl.setting_id==string(name),1);
if isempty(idx), error('TripLens:MissingSetting','Missing setting %s',name); end
value=str2double(string(tbl.value(idx)));
if isnan(value), error('TripLens:BadSetting','Non-numeric setting %s',name); end
end

function code=buildFunctionCode(recvN,lockN,breakerN,uvN,uvPickupKv,stLowMw)
lines={ ...
'function y = A_Logic_State(u)' ...
'persistent tripCount lockoutState cbTripState uvACount uvBCount' ...
'if isempty(tripCount)' ...
'    tripCount = 0;' ...
'    lockoutState = false;' ...
'    cbTripState = false;' ...
'    uvACount = 0;' ...
'    uvBCount = 0;' ...
'end' ...
sprintf('RECV_N = %.17g;',recvN) ...
sprintf('LOCK_N = %.17g;',lockN) ...
sprintf('BREAKER_N = %.17g;',breakerN) ...
sprintf('UV_N = %.17g;',uvN) ...
sprintf('UV_PICKUP = %.17g;',uvPickupKv) ...
sprintf('ST_LOW_MW = %.17g;',stLowMw) ...
'gtTrip = u(1) > 0.5;' ...
'relayHealthy = u(2) > 0.5;' ...
'resetCmd = u(3) > 0.5;' ...
'busAV = u(5);' ...
'busBV = u(6);' ...
'busANative = u(7) > 0.5;' ...
'busBNative = u(8) > 0.5;' ...
'busAFault = u(9) > 0.5;' ...
'busBFault = u(10) > 0.5;' ...
'stMw = u(11);' ...
'autoTie = u(12) > 0.5;' ...
'allowParallel = u(13) > 0.5;' ...
'if gtTrip' ...
'    tripCount = tripCount + 1;' ...
'else' ...
'    tripCount = 0;' ...
'end' ...
'recvState = gtTrip && relayHealthy && (tripCount > RECV_N);' ...
'if gtTrip && relayHealthy && (tripCount > LOCK_N)' ...
'    lockoutState = true;' ...
'end' ...
'if gtTrip && relayHealthy && (tripCount > BREAKER_N)' ...
'    cbTripState = true;' ...
'end' ...
'if resetCmd' ...
'    lockoutState = false;' ...
'    cbTripState = false;' ...
'end' ...
'if busAV < UV_PICKUP' ...
'    uvACount = uvACount + 1;' ...
'else' ...
'    uvACount = 0;' ...
'end' ...
'if busBV < UV_PICKUP' ...
'    uvBCount = uvBCount + 1;' ...
'else' ...
'    uvBCount = 0;' ...
'end' ...
'uvA = uvACount > UV_N;' ...
'uvB = uvBCount > UV_N;' ...
'candidateA = uvA && (~busANative) && busBNative && (~busAFault);' ...
'candidateB = uvB && (~busBNative) && busANative && (~busBFault);' ...
'parallelRisk = busANative && busBNative && (~allowParallel);' ...
'tiePerm = autoTie && (candidateA || candidateB) && (~parallelRisk) && (~(busAFault && busBFault));' ...
'stLow = abs(stMw) < ST_LOW_MW;' ...
'y = zeros(7,1);' ...
'y(1) = double(recvState);' ...
'y(2) = double(lockoutState);' ...
'y(3) = double(cbTripState);' ...
'y(4) = double(uvA);' ...
'y(5) = double(uvB);' ...
'y(6) = double(tiePerm);' ...
'y(7) = double(stLow);' ...
'end'};
code=strjoin(lines,newline);
end

function t=firstTrueTime(yout,index)
sig=yout.getElement(index).Values;
idx=find(logical(sig.Data),1,'first');
if isempty(idx), t=NaN; else, t=sig.Time(idx); end
end

