function build_a_logic_core()
%BUILD_A_LOGIC_CORE Generate the first A-program -> ECMS Simulink logic module.
% Physical quantities are inputs. This module does not synthesize V/I/f/power.

repoRoot = getenv('GITHUB_WORKSPACE');
if isempty(repoRoot)
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
end
logicDir = fullfile(repoRoot,'ecms_logic');
outDir = fullfile(repoRoot,'outputs');
if ~isfolder(outDir), mkdir(outDir); end

cfg = readtable(fullfile(logicDir,'a_logic_settings_v1.csv'), ...
    'TextType','string','VariableNamingRule','preserve');
getv = @(name) settingValue(cfg,name);

sampleMs = getv('LOGIC_SAMPLE_TIME_MS');
Ts = sampleMs / 1000;
recvN = round(getv('TRIP_RECEIVE_DELAY_MS') / sampleMs);
lockTotalN = round((getv('TRIP_RECEIVE_DELAY_MS') + getv('LOCKOUT_OPERATE_DELAY_MS')) / sampleMs);
breakerN = round(getv('GT_BREAKER_OPEN_DELAY_MS') / sampleMs);
uvN = round(getv('UNDERVOLTAGE_DELAY_MS') / sampleMs);
uvPickup = getv('UNDERVOLTAGE_PICKUP_PU');
stLowPu = getv('ST_TRIP_POWER_PU');

modelName = 'TripLens_ECMS_A_Logic_Core';
modelPath = fullfile(outDir,[modelName '.slx']);
if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelPath), delete(modelPath); end
new_system(modelName);
set_param(modelName, ...
    'SolverType','Fixed-step', ...
    'Solver','FixedStepDiscrete', ...
    'FixedStep',num2str(Ts,'%.12g'), ...
    'StopTime','1.2', ...
    'SaveOutput','on', ...
    'OutputSaveName','yout', ...
    'SaveFormat','Dataset', ...
    'Description',[ ...
      'TripLens ECMS A-program logic core v1. Tag Master binding pending. ' ...
      'Physical bus voltage, topology, breaker feedback and ST power enter as external twin inputs.']);

inputNames = { ...
    'gt_trip_cmd', ...
    'relay_86gt_healthy', ...
    'cb_52gt_reset_cmd', ...
    'cb_52gt_closed_fb', ...
    'bus_a_voltage_pu', ...
    'bus_b_voltage_pu', ...
    'bus_a_native_live', ...
    'bus_b_native_live', ...
    'bus_a_fault_active', ...
    'bus_b_fault_active', ...
    'stg_power_pu', ...
    'auto_bus_tie_enable', ...
    'allow_source_parallel'};
inputTypes = { ...
    'boolean','boolean','boolean','boolean', ...
    'double','double', ...
    'boolean','boolean','boolean','boolean', ...
    'double','boolean','boolean'};
outputNames = { ...
    'relay_86gt_trip_received', ...
    'relay_86gt_operated', ...
    'cb_52gt_trip_cmd', ...
    'bus_a_27uv_operate', ...
    'bus_b_27uv_operate', ...
    'cb_tie_ab_auto_close_permissive', ...
    'stg_low_state'};

for k = 1:numel(inputNames)
    y = 35 + (k-1)*42;
    p = [40 y 185 y+22];
    b = [modelName '/' inputNames{k}];
    add_block('simulink/Sources/In1',b,'Position',p,'Port',num2str(k));
    set_param(b,'OutDataTypeStr',inputTypes{k});
end

mfPath = [modelName '/A_Logic_State'];
add_block('simulink/User-Defined Functions/MATLAB Function',mfPath, ...
    'Position',[330 105 690 515]);
rt = sfroot;
chart = rt.find('-isa','Stateflow.EMChart','Path',mfPath);
if isempty(chart)
    error('TripLens:MATLABFunctionChart','Could not resolve MATLAB Function chart.');
end
chart.Script = buildFunctionCode(recvN,lockTotalN,breakerN,uvN,uvPickup,stLowPu);
set_param(modelName,'SimulationCommand','update');

for k = 1:numel(outputNames)
    y = 105 + (k-1)*58;
    p = [835 y 1010 y+22];
    b = [modelName '/' outputNames{k}];
    add_block('simulink/Sinks/Out1',b,'Position',p,'Port',num2str(k));
end
set_param(modelName,'SimulationCommand','update');

mfPorts = get_param(mfPath,'PortHandles');
for k = 1:numel(inputNames)
    inPorts = get_param([modelName '/' inputNames{k}],'PortHandles');
    add_line(modelName,inPorts.Outport,mfPorts.Inport(k),'autorouting','on');
end
for k = 1:numel(outputNames)
    outPorts = get_param([modelName '/' outputNames{k}],'PortHandles');
    lineH = add_line(modelName,mfPorts.Outport(k),outPorts.Inport,'autorouting','on');
    set_param(lineH,'Name',outputNames{k});
end

save_system(modelName,modelPath);

matlabDriveCopy = '';
try
    mdrive = '';
    if exist('matlabdrive','file') == 2
        mdrive = matlabdrive;
    end
    if isempty(mdrive)
        candidate = fullfile(getenv('USERPROFILE'),'MATLAB Drive');
        if isfolder(candidate), mdrive = candidate; end
    end
    if ~isempty(mdrive) && isfolder(mdrive)
        targetDir = fullfile(mdrive,'TripLens_ECMS_DigitalTwin','models');
        if ~isfolder(targetDir), mkdir(targetDir); end
        matlabDriveCopy = fullfile(targetDir,[modelName '.slx']);
        copyfile(modelPath,matlabDriveCopy,'f');
    end
catch copyErr
    fprintf('MATLAB Drive copy skipped: %s\n',copyErr.message);
    matlabDriveCopy = '';
end

% Standalone 1 ms logic smoke test. The harness data are synthetic test inputs
% only; the production model itself never synthesizes physical quantities.
t = (0:Ts:1.2)';
N = numel(t);
inputs = cell(1,numel(inputNames));
inputs{1} = t >= 0.500;                 % GT Trip command
inputs{2} = true(N,1);                  % relay healthy
inputs{3} = false(N,1);                 % reset not asserted
inputs{4} = true(N,1);                  % 52GT feedback closed (reserved)
inputs{5} = ones(N,1); inputs{5}(t >= 0.700) = 0.50; % BUS-A UV test stimulus
inputs{6} = ones(N,1);
inputs{7} = true(N,1); inputs{7}(t >= 0.700) = false; % BUS-A native source loss test
inputs{8} = true(N,1);
inputs{9} = false(N,1);
inputs{10} = false(N,1);
inputs{11} = ones(N,1);
inputs{12} = false(N,1);                % auto tie disabled by A setting
inputs{13} = false(N,1);                % source parallel prohibited

ds = Simulink.SimulationData.Dataset;
for k = 1:numel(inputNames)
    tsx = timeseries(inputs{k},t);
    tsx.Name = inputNames{k};
    tsx = setinterpmethod(tsx,'zoh');
    ds = ds.addElement(tsx,inputNames{k});
end
simIn = Simulink.SimulationInput(modelName);
simIn = simIn.setExternalInput(ds);
simIn = simIn.setModelParameter('StopTime','1.2');
simOut = sim(simIn);
yout = simOut.yout;

actualReceive = firstTrueTime(yout,1);
actualLockout = firstTrueTime(yout,2);
actualBreaker = firstTrueTime(yout,3);
actualUvA = firstTrueTime(yout,4);
tieSig = yout.getElement(6).Values;
stLowSig = yout.getElement(7).Values;

expectedReceive = 0.500 + getv('TRIP_RECEIVE_DELAY_MS')/1000;
expectedLockout = 0.500 + (getv('TRIP_RECEIVE_DELAY_MS') + getv('LOCKOUT_OPERATE_DELAY_MS'))/1000;
expectedBreaker = 0.500 + getv('GT_BREAKER_OPEN_DELAY_MS')/1000;
expectedUvA = 0.700 + getv('UNDERVOLTAGE_DELAY_MS')/1000;
tol = Ts + 1e-9;
checks = struct();
checks.gt_trip_receive = abs(actualReceive-expectedReceive) <= tol;
checks.gt_86_lockout = abs(actualLockout-expectedLockout) <= tol;
checks.gt_52_trip = abs(actualBreaker-expectedBreaker) <= tol;
checks.bus_a_27uv = abs(actualUvA-expectedUvA) <= tol;
checks.tie_disabled_default = ~any(logical(tieSig.Data));
checks.st_low_not_fabricated = ~any(logical(stLowSig.Data));
pass = all(structfun(@(x) logical(x),checks));

report = struct();
report.model = modelName;
report.model_path = modelPath;
report.matlab_drive_copy = matlabDriveCopy;
report.tag_master_binding = 'PENDING';
report.logic_sample_time_ms = sampleMs;
report.source_logic = 'A program reference implementation';
report.migrated_v1 = outputNames;
report.physical_inputs_not_synthesized = { ...
    'bus_a_voltage_pu','bus_b_voltage_pu','cb_52gt_closed_fb', ...
    'bus_a_native_live','bus_b_native_live','stg_power_pu'};
report.expected_times_s = struct( ...
    'trip_receive',expectedReceive,'lockout',expectedLockout, ...
    'breaker_trip',expectedBreaker,'bus_a_uv',expectedUvA);
report.actual_times_s = struct( ...
    'trip_receive',actualReceive,'lockout',actualLockout, ...
    'breaker_trip',actualBreaker,'bus_a_uv',actualUvA);
report.checks = checks;
report.pass = pass;
report.note = ['V1 migrates protection/control logic only. All inherited settings are provisional. ' ...
    '52ST automatic opening, synchronism, 50/51 physics, motor protection and final tag bindings remain deferred.'];

reportPath = fullfile(outDir,'ecms_a_logic_core_report.json');
fid = fopen(reportPath,'w','n','UTF-8');
if fid < 0, error('TripLens:ReportWrite','Could not write logic report.'); end
fprintf(fid,'%s',jsonencode(report,'PrettyPrint',true));
fclose(fid);

fprintf('TRIPLENS A->ECMS LOGIC CORE BUILT\n');
fprintf('MODEL=%s\n',modelPath);
fprintf('TRIP_RECEIVE=%.3f LOCKOUT=%.3f CB52GT_TRIP=%.3f BUS_A_UV=%.3f\n', ...
    actualReceive,actualLockout,actualBreaker,actualUvA);
fprintf('TAG_MASTER_BINDING=PENDING\n');
fprintf('PASS=%d\n',pass);
if ~pass
    error('TripLens:ALogicSmokeFailed','A-program ECMS logic smoke test failed.');
end
close_system(modelName,0);
end

function value = settingValue(tbl,name)
idx = find(tbl.setting_id == string(name),1);
if isempty(idx), error('TripLens:MissingSetting','Missing setting %s',name); end
value = str2double(string(tbl.value(idx)));
if isnan(value), error('TripLens:BadSetting','Non-numeric setting %s',name); end
end

function code = buildFunctionCode(recvN,lockTotalN,breakerN,uvN,uvPickup,stLowPu)
lines = { ...
'function [relay_86gt_trip_received, relay_86gt_operated, cb_52gt_trip_cmd, bus_a_27uv_operate, bus_b_27uv_operate, cb_tie_ab_auto_close_permissive, stg_low_state] = A_Logic_State(gt_trip_cmd, relay_86gt_healthy, cb_52gt_reset_cmd, cb_52gt_closed_fb, bus_a_voltage_pu, bus_b_voltage_pu, bus_a_native_live, bus_b_native_live, bus_a_fault_active, bus_b_fault_active, stg_power_pu, auto_bus_tie_enable, allow_source_parallel)' ...
'%#codegen' ...
sprintf('RECV_N = uint32(%d);',recvN) ...
sprintf('LOCK_TOTAL_N = uint32(%d);',lockTotalN) ...
sprintf('BREAKER_N = uint32(%d);',breakerN) ...
sprintf('UV_N = uint32(%d);',uvN) ...
sprintf('UV_PICKUP = %.17g;',uvPickup) ...
sprintf('ST_LOW_PU = %.17g;',stLowPu) ...
'persistent prevTrip tripCount recvIssued lockIssued cbIssued recvState lockoutState cbTripState uvACount uvBCount' ...
'if isempty(prevTrip)' ...
'    prevTrip = false; tripCount = uint32(0);' ...
'    recvIssued = false; lockIssued = false; cbIssued = false;' ...
'    recvState = false; lockoutState = false; cbTripState = false;' ...
'    uvACount = uint32(0); uvBCount = uint32(0);' ...
'end' ...
'if gt_trip_cmd && ~prevTrip' ...
'    tripCount = uint32(0); recvIssued = false; lockIssued = false; cbIssued = false; recvState = false;' ...
'end' ...
'if gt_trip_cmd' ...
'    tripCount = tripCount + uint32(1);' ...
'    if relay_86gt_healthy && ~recvIssued && tripCount > RECV_N' ...
'        recvState = true; recvIssued = true;' ...
'    end' ...
'    if relay_86gt_healthy && ~lockIssued && tripCount > LOCK_TOTAL_N' ...
'        lockoutState = true; lockIssued = true;' ...
'    end' ...
'    if relay_86gt_healthy && ~cbIssued && tripCount > BREAKER_N' ...
'        cbTripState = true; cbIssued = true;' ...
'    end' ...
'else' ...
'    tripCount = uint32(0); recvState = false;' ...
'end' ...
'if cb_52gt_reset_cmd' ...
'    lockoutState = false; cbTripState = false;' ...
'end' ...
'if bus_a_voltage_pu < UV_PICKUP' ...
'    uvACount = uvACount + uint32(1);' ...
'else' ...
'    uvACount = uint32(0);' ...
'end' ...
'if bus_b_voltage_pu < UV_PICKUP' ...
'    uvBCount = uvBCount + uint32(1);' ...
'else' ...
'    uvBCount = uint32(0);' ...
'end' ...
'bus_a_27uv_operate = uvACount > UV_N;' ...
'bus_b_27uv_operate = uvBCount > UV_N;' ...
'candidateA = bus_a_27uv_operate && ~bus_a_native_live && bus_b_native_live && ~bus_a_fault_active;' ...
'candidateB = bus_b_27uv_operate && ~bus_b_native_live && bus_a_native_live && ~bus_b_fault_active;' ...
'parallelRisk = bus_a_native_live && bus_b_native_live && ~allow_source_parallel;' ...
'cb_tie_ab_auto_close_permissive = auto_bus_tie_enable && (candidateA || candidateB) && ~parallelRisk && ~(bus_a_fault_active && bus_b_fault_active);' ...
'stg_low_state = abs(stg_power_pu) < ST_LOW_PU;' ...
'relay_86gt_trip_received = recvState;' ...
'relay_86gt_operated = lockoutState;' ...
'cb_52gt_trip_cmd = cbTripState;' ...
'prevTrip = gt_trip_cmd;' ...
'% cb_52gt_closed_fb is intentionally reserved for validated fail-to-open logic.' ...
'if cb_52gt_closed_fb && false' ...
'    cb_52gt_trip_cmd = cb_52gt_trip_cmd;' ...
'end' ...
'end'};
code = strjoin(lines,newline);
end

function t = firstTrueTime(yout,index)
sig = yout.getElement(index).Values;
idx = find(logical(sig.Data),1,'first');
if isempty(idx), t = NaN; else, t = sig.Time(idx); end
end
