function build_a_logic_core()
%BUILD_A_LOGIC_CORE Generate/validate A-program -> ECMS Simulink logic core.
% Physical quantities are external inputs. No V/I/f/power is synthesized here.
% Protection layering:
%   Layer 1 alarm inputs: drum HH/LL booleans from first-order alarm logic.
%   Layer 2 common trip matrix: GT Trip -> ST Trip, Drum HH -> ST only,
%   Drum LL -> GT + ST simultaneous trip requests.
%   Layer 3 actuation: GT 86/52GT and ST 52ST breaker trip latches.

repoRoot = getenv('GITHUB_WORKSPACE');
if isempty(repoRoot)
    repoRoot = fileparts(fileparts(mfilename('fullpath')));
end
logicDir = fullfile(repoRoot,'ecms_logic');
outDir = fullfile(repoRoot,'outputs');
if ~isfolder(outDir), mkdir(outDir); end

cfg = readtable(fullfile(logicDir,'a_logic_settings_v1.csv'), ...
    'TextType','string','VariableNamingRule','preserve');
getv = @(name) settingValue(cfg,name);
sampleMs = getv('LOGIC_SAMPLE_TIME_MS');
Ts = sampleMs/1000;
recvN = round(getv('TRIP_RECEIVE_DELAY_MS')/sampleMs);
lockN = round((getv('TRIP_RECEIVE_DELAY_MS')+getv('LOCKOUT_OPERATE_DELAY_MS'))/sampleMs);
gtBreakerN = round(getv('GT_BREAKER_OPEN_DELAY_MS')/sampleMs);
stBreakerN = round(getv('ST_BREAKER_OPEN_DELAY_MS')/sampleMs);
uvN = round(getv('UNDERVOLTAGE_DELAY_MS')/sampleMs);
uvPickupKv = getv('BUS_UNDERVOLTAGE_PICKUP_KV');
stLowMw = getv('ST_LOW_POWER_MW');

modelName = 'TripLens_ECMS_A_Logic_Core';
modelPath = fullfile(outDir,[modelName '.slx']);
if bdIsLoaded(modelName), close_system(modelName,0); end
if isfile(modelPath), delete(modelPath); end
new_system(modelName);
set_param(modelName,'SolverType','Fixed-step','Solver','FixedStepDiscrete', ...
    'FixedStep',num2str(Ts,'%.12g'),'StopTime','1.2', ...
    'SaveOutput','on','OutputSaveName','yout','SaveFormat','Dataset', ...
    'Description',['TripLens A-program logic migration core v3. Layer1 first-order alarms feed ' ...
    'a common GT/ST protection matrix. Physical states are supplied by Electrical/Thermo twins.']);

inputNames = {'gt_trip_cmd','st_trip_cmd', ...
    'hp_drum_level_hh','hp_drum_level_ll', ...
    'ip_drum_level_hh','ip_drum_level_ll', ...
    'lp_drum_level_hh','lp_drum_level_ll', ...
    'relay_86gt_healthy','cb_52gt_reset_cmd','cb_52gt_closed_fb', ...
    'cb_52st_reset_cmd','cb_52st_closed_fb', ...
    'bus_a_voltage_kv','bus_b_voltage_kv', ...
    'bus_a_native_live','bus_b_native_live','bus_a_fault_active', ...
    'bus_b_fault_active','stg_power_mw','auto_bus_tie_enable', ...
    'allow_source_parallel'};
inputTypes = {'boolean','boolean','boolean','boolean','boolean','boolean','boolean','boolean', ...
    'boolean','boolean','boolean','boolean','boolean','double','double', ...
    'boolean','boolean','boolean','boolean','double','boolean','boolean'};
outputNames = {'gt_trip_request','st_trip_request', ...
    'relay_86gt_trip_received','relay_86gt_operated','cb_52gt_trip_cmd', ...
    'cb_52st_trip_cmd','bus_a_27uv_operate','bus_b_27uv_operate', ...
    'cb_tie_ab_auto_close_permissive','stg_low_state'};

for k = 1:numel(inputNames)
    y = 35+(k-1)*42;
    inPath = [modelName '/' inputNames{k}];
    add_block('simulink/Sources/In1',inPath,'Position',[25 y 155 y+22],'Port',num2str(k));
    set_param(inPath,'OutDataTypeStr',inputTypes{k});
    cvtPath = [modelName '/to_double_' num2str(k)];
    add_block('simulink/Signal Attributes/Data Type Conversion',cvtPath, ...
        'OutDataTypeStr','double','Position',[180 y 225 y+22]);
    add_line(modelName,[inputNames{k} '/1'],['to_double_' num2str(k) '/1'],'autorouting','on');
end

commonName = 'Common_Trip_Matrix';
gtName = 'GT_Trip_Protection';
stTripName = 'ST_Trip_Actuation';
busName = 'Bus_Protection_Transfer';
stName = 'ST_State_Monitor';

addLogicSubsystem(modelName,commonName, ...
    {'gt_trip_cmd','st_trip_cmd','hp_drum_level_hh','hp_drum_level_ll', ...
     'ip_drum_level_hh','ip_drum_level_ll','lp_drum_level_hh','lp_drum_level_ll'}, ...
    outputNames(1:2),buildCommonTripFunctionCode(), ...
    [330 45 610 225],[1 0.86 0.72]);
addLogicSubsystem(modelName,gtName, ...
    {'gt_trip_request','relay_86gt_healthy','cb_52gt_reset_cmd','cb_52gt_closed_fb'}, ...
    outputNames(3:5),buildGtFunctionCode(recvN,lockN,gtBreakerN), ...
    [675 45 955 220],[1 0.82 0.82]);
addLogicSubsystem(modelName,stTripName, ...
    {'st_trip_request','cb_52st_reset_cmd','cb_52st_closed_fb'}, ...
    outputNames(6),buildStTripFunctionCode(stBreakerN), ...
    [675 250 955 370],[1 0.86 0.86]);
addLogicSubsystem(modelName,busName, ...
    {'bus_a_voltage_kv','bus_b_voltage_kv','bus_a_native_live','bus_b_native_live', ...
     'bus_a_fault_active','bus_b_fault_active','auto_bus_tie_enable','allow_source_parallel'}, ...
    outputNames(7:9),buildBusFunctionCode(uvN,uvPickupKv), ...
    [330 350 610 595],[1 0.92 0.76]);
addLogicSubsystem(modelName,stName,{'stg_power_mw'},outputNames(10), ...
    buildStFunctionCode(stLowMw),[330 640 610 725],[0.82 0.91 1]);

commonInputs = 1:8;
for k=1:numel(commonInputs)
    add_line(modelName,['to_double_' num2str(commonInputs(k)) '/1'], ...
        [commonName '/' num2str(k)],'autorouting','on');
end

% Resolved GT request drives the existing 86GT -> 52GT protection path.
add_line(modelName,[commonName '/1'],[gtName '/1'],'autorouting','on');
add_line(modelName,'to_double_9/1',[gtName '/2'],'autorouting','on');
add_line(modelName,'to_double_10/1',[gtName '/3'],'autorouting','on');
add_line(modelName,'to_double_11/1',[gtName '/4'],'autorouting','on');

% Resolved ST request drives the independent ST breaker trip path.
add_line(modelName,[commonName '/2'],[stTripName '/1'],'autorouting','on');
add_line(modelName,'to_double_12/1',[stTripName '/2'],'autorouting','on');
add_line(modelName,'to_double_13/1',[stTripName '/3'],'autorouting','on');

busInputs = [14 15 16 17 18 19 21 22];
for k=1:numel(busInputs)
    add_line(modelName,['to_double_' num2str(busInputs(k)) '/1'], ...
        [busName '/' num2str(k)],'autorouting','on');
end
add_line(modelName,'to_double_20/1',[stName '/1'],'autorouting','on');

outputSources = {[commonName '/1'],[commonName '/2'], ...
    [gtName '/1'],[gtName '/2'],[gtName '/3'],[stTripName '/1'], ...
    [busName '/1'],[busName '/2'],[busName '/3'],[stName '/1']};
for k = 1:numel(outputNames)
    y = 100+(k-1)*58;
    cvtPath = [modelName '/to_bool_' num2str(k)];
    add_block('simulink/Signal Attributes/Data Type Conversion',cvtPath, ...
        'OutDataTypeStr','boolean','Position',[1060 y 1110 y+22]);
    outPath = [modelName '/' outputNames{k}];
    add_block('simulink/Sinks/Out1',outPath,'Position',[1160 y 1350 y+22],'Port',num2str(k));
    add_line(modelName,outputSources{k},['to_bool_' num2str(k) '/1'],'autorouting','on');
    add_line(modelName,['to_bool_' num2str(k) '/1'],[outputNames{k} '/1'],'autorouting','on');
end
set_param(modelName,'SimulationCommand','update');
save_system(modelName,modelPath);

matlabDriveCopy = '';
try
    mdrive = '';
    if exist('matlabdrive','file') == 2, mdrive = matlabdrive; end
    if isempty(mdrive)
        candidate = fullfile(getenv('USERPROFILE'),'MATLAB Drive');
        if isfolder(candidate), mdrive = candidate; end
    end
    if ~isempty(mdrive) && isfolder(mdrive)
        targetDir = fullfile(mdrive,'TripLens_ECMS_DigitalTwin','models');
        if ~isfolder(targetDir), mkdir(targetDir); end
        matlabDriveCopy = fullfile(targetDir,[modelName '.slx']);
        copyfile(modelPath,matlabDriveCopy,'f');
    end
catch copyErr
    fprintf('MATLAB Drive copy skipped: %s\n',copyErr.message);
    matlabDriveCopy = '';
end

% Main smoke case: direct GT Trip must intertrip ST.
t = (0:Ts:1.2)'; N = numel(t);
inputs = baselineInputs(N);
inputs{1}=t>=0.500;                % GT Trip command
inputs{14}(t>=0.700)=3.45;         % BUS-A undervoltage
inputs{16}(t>=0.700)=false;        % BUS-A native source lost

yout = simulateInputs(modelName,inputNames,inputs,t);
actualGtReq=firstTrueTime(yout,1);
actualStReq=firstTrueTime(yout,2);
actualReceive=firstTrueTime(yout,3);
actualLockout=firstTrueTime(yout,4);
actualGtBreaker=firstTrueTime(yout,5);
actualStBreaker=firstTrueTime(yout,6);
actualUvA=firstTrueTime(yout,7);
tieSig=yout.getElement(9).Values;
stLowSig=yout.getElement(10).Values;
expectedGtReq=0.500;
expectedStReq=0.500;
expectedReceive=0.500+getv('TRIP_RECEIVE_DELAY_MS')/1000;
expectedLockout=0.500+(getv('TRIP_RECEIVE_DELAY_MS')+getv('LOCKOUT_OPERATE_DELAY_MS'))/1000;
expectedGtBreaker=0.500+getv('GT_BREAKER_OPEN_DELAY_MS')/1000;
expectedStBreaker=0.500+getv('ST_BREAKER_OPEN_DELAY_MS')/1000;
expectedUvA=0.700+getv('UNDERVOLTAGE_DELAY_MS')/1000;
tol=Ts+1e-9;
checks=struct();
checks.gt_request_from_direct_gt=abs(actualGtReq-expectedGtReq)<=tol;
checks.st_intertrip_from_direct_gt=abs(actualStReq-expectedStReq)<=tol;
checks.gt_trip_receive=abs(actualReceive-expectedReceive)<=tol;
checks.gt_86_lockout=abs(actualLockout-expectedLockout)<=tol;
checks.gt_52_trip=abs(actualGtBreaker-expectedGtBreaker)<=tol;
checks.st_52_trip_from_gt=abs(actualStBreaker-expectedStBreaker)<=tol;
checks.bus_a_27uv=abs(actualUvA-expectedUvA)<=tol;
checks.tie_disabled_default=~any(logical(tieSig.Data));
checks.st_low_not_trip_source=~any(logical(stLowSig.Data));

% Protection-matrix regression: every drum HH trips ST only; every drum LL trips both.
matrixCases = { ...
    'hp_hh',3,false,true; ...
    'ip_hh',5,false,true; ...
    'lp_hh',7,false,true; ...
    'hp_ll',4,true,true; ...
    'ip_ll',6,true,true; ...
    'lp_ll',8,true,true; ...
    'direct_st',2,false,true};
for c=1:size(matrixCases,1)
    caseName=matrixCases{c,1};
    inputIndex=matrixCases{c,2};
    expectGt=matrixCases{c,3};
    expectSt=matrixCases{c,4};
    caseInputs=baselineInputs(N);
    caseInputs{inputIndex}=t>=0.200;
    caseOut=simulateInputs(modelName,inputNames,caseInputs,t);
    gtReqTime=firstTrueTime(caseOut,1);
    stReqTime=firstTrueTime(caseOut,2);
    gtBreakerTime=firstTrueTime(caseOut,5);
    stBreakerTime=firstTrueTime(caseOut,6);
    if expectGt
        gtOk=abs(gtReqTime-0.200)<=tol && ...
            abs(gtBreakerTime-(0.200+getv('GT_BREAKER_OPEN_DELAY_MS')/1000))<=tol;
    else
        gtOk=isnan(gtReqTime) && isnan(gtBreakerTime);
    end
    if expectSt
        stOk=abs(stReqTime-0.200)<=tol && ...
            abs(stBreakerTime-(0.200+getv('ST_BREAKER_OPEN_DELAY_MS')/1000))<=tol;
    else
        stOk=isnan(stReqTime) && isnan(stBreakerTime);
    end
    checks.([caseName '_gt_path'])=gtOk;
    checks.([caseName '_st_path'])=stOk;
end
pass=all(structfun(@(x) logical(x),checks));

report=struct(); report.model=modelName; report.model_path=modelPath;
report.matlab_drive_copy=matlabDriveCopy; report.tag_master_binding='CORE_RAW_PLUS_LAYER1_ALARMS';
report.logic_sample_time_ms=sampleMs; report.source_logic='Common trip matrix + A program reference implementation';
report.common_trip_matrix=fullfile(logicDir,'common_trip_matrix_v1.csv');
report.migrated_v2=outputNames;
report.protection_policy=struct( ...
    'gt_trip_intertrips_st',true, ...
    'drum_hh_action','ST_ONLY', ...
    'drum_ll_action','GT_AND_ST');
report.physical_inputs_not_synthesized={'bus_a_voltage_kv','bus_b_voltage_kv', ...
    'cb_52gt_closed_fb','cb_52st_closed_fb','bus_a_native_live','bus_b_native_live','stg_power_mw'};
report.layer1_inputs={'hp_drum_level_hh','hp_drum_level_ll','ip_drum_level_hh', ...
    'ip_drum_level_ll','lp_drum_level_hh','lp_drum_level_ll'};
report.expected_times_s=struct('gt_request',expectedGtReq,'st_request',expectedStReq, ...
    'trip_receive',expectedReceive,'lockout',expectedLockout, ...
    'gt_breaker_trip',expectedGtBreaker,'st_breaker_trip',expectedStBreaker, ...
    'bus_a_uv',expectedUvA);
report.actual_times_s=struct('gt_request',actualGtReq,'st_request',actualStReq, ...
    'trip_receive',actualReceive,'lockout',actualLockout, ...
    'gt_breaker_trip',actualGtBreaker,'st_breaker_trip',actualStBreaker, ...
    'bus_a_uv',actualUvA);
report.checks=checks; report.pass=pass;
report.logic_hierarchy={commonName,gtName,stTripName,busName,stName};
report.note=['V3 keeps raw/first-order alarm generation separate from Layer2 trip decisions. ' ...
    'Drum HH/LL booleans are external Layer1 inputs. GT Trip intertrips ST; drum HH trips ST only; ' ...
    'drum LL trips both GT and ST. Breaker delays remain virtual-model provisional values until ' ...
    'approved plant C&E/breaker timing is available.'];
reportPath=fullfile(outDir,'ecms_a_logic_core_report.json');
fid=fopen(reportPath,'w','n','UTF-8');
if fid<0, error('TripLens:ReportWrite','Could not write logic report.'); end
fprintf(fid,'%s',jsonencode(report,'PrettyPrint',true)); fclose(fid);
fprintf('TRIPLENS A->ECMS LOGIC CORE BUILT\nMODEL=%s\nPASS=%d\n',modelPath,pass);
if ~pass, error('TripLens:ALogicSmokeFailed','A-program ECMS logic smoke test failed.'); end
close_system(modelName,0);
end

function inputs=baselineInputs(N)
inputs=cell(1,22);
for k=1:22, inputs{k}=false(N,1); end
inputs{9}=true(N,1);   % 86GT healthy
inputs{11}=true(N,1);  % 52GT closed feedback
inputs{13}=true(N,1);  % 52ST closed feedback
inputs{14}=6.9*ones(N,1);
inputs{15}=6.9*ones(N,1);
inputs{16}=true(N,1);
inputs{17}=true(N,1);
inputs{20}=277*ones(N,1);
end

function yout=simulateInputs(modelName,inputNames,inputs,t)
ds = Simulink.SimulationData.Dataset;
for k=1:numel(inputNames)
    tsx = timeseries(inputs{k},t); tsx.Name=inputNames{k}; tsx=setinterpmethod(tsx,'zoh');
    ds = ds.addElement(tsx,inputNames{k});
end
simIn = Simulink.SimulationInput(modelName);
simIn = simIn.setExternalInput(ds);
simIn = simIn.setModelParameter('StopTime',num2str(t(end),'%.12g'));
simOut = sim(simIn);
yout = simOut.yout;
end

function value=settingValue(tbl,name)
idx=find(tbl.setting_id==string(name),1);
if isempty(idx), error('TripLens:MissingSetting','Missing setting %s',name); end
value=str2double(string(tbl.value(idx)));
if isnan(value), error('TripLens:BadSetting','Non-numeric setting %s',name); end
end

function addLogicSubsystem(modelName,subName,inputNames,outputNames,code,position,color)
subPath=[modelName '/' subName];
add_block('simulink/Ports & Subsystems/Subsystem',subPath,'Position',position, ...
    'BackgroundColor',mat2str(color),'ForegroundColor','black','FontWeight','bold');
children=find_system(subPath,'SearchDepth',1,'Type','Block');
children=children(~strcmp(children,subPath));
lines=find_system(subPath,'FindAll','on','SearchDepth',1,'Type','line');
if ~isempty(lines), delete_line(lines); end
for k=1:numel(children), delete_block(children{k}); end
for k=1:numel(inputNames)
    y=30+(k-1)*38;
    add_block('simulink/Sources/In1',[subPath '/' inputNames{k}], ...
        'Port',num2str(k),'Position',[25 y 155 y+20]);
end
logicPath=[subPath '/Logic'];
logicHeight=max(105,45+numel(inputNames)*30);
add_block('simulink/User-Defined Functions/MATLAB Function',logicPath, ...
    'Position',[220 45 480 logicHeight]);
rt=sfroot;
chart=rt.find('-isa','Stateflow.EMChart','Path',logicPath);
if isempty(chart), error('TripLens:MATLABFunctionChart','Could not resolve %s.',logicPath); end
chart.Script=code;
for k=1:numel(outputNames)
    y=55+(k-1)*55;
    add_block('simulink/Sinks/Out1',[subPath '/' outputNames{k}], ...
        'Port',num2str(k),'Position',[550 y 750 y+20]);
end
set_param(modelName,'SimulationCommand','update');
for k=1:numel(inputNames)
    add_line(subPath,[inputNames{k} '/1'],['Logic/' num2str(k)],'autorouting','on');
end
for k=1:numel(outputNames)
    add_line(subPath,['Logic/' num2str(k)],[outputNames{k} '/1'],'autorouting','on');
end
set_param(subPath,'Description',sprintf('TripLens ECMS hierarchy: %s',strrep(subName,'_',' ')));
end

function code=buildCommonTripFunctionCode()
lines={ ...
'function [gtReq,stReq] = Logic(gtTripCmd,stTripCmd,hpHH,hpLL,ipHH,ipLL,lpHH,lpLL)' ...
'gtTripCmd = gtTripCmd > 0.5;' ...
'stTripCmd = stTripCmd > 0.5;' ...
'hpHH = hpHH > 0.5; hpLL = hpLL > 0.5;' ...
'ipHH = ipHH > 0.5; ipLL = ipLL > 0.5;' ...
'lpHH = lpHH > 0.5; lpLL = lpLL > 0.5;' ...
'anyHH = hpHH || ipHH || lpHH;' ...
'anyLL = hpLL || ipLL || lpLL;' ...
'gtReq = gtTripCmd || anyLL;' ...
'stReq = stTripCmd || gtTripCmd || anyHH || anyLL;' ...
'end'};
code=strjoin(lines,newline);
end

function code=buildGtFunctionCode(recvN,lockN,breakerN)
lines={ ...
'function [recvState,lockoutState,cbTripState] = Logic(gtTrip,relayHealthy,resetCmd,cbClosed)' ...
'persistent tripCount lockoutLatch cbTripLatch' ...
'if isempty(tripCount)' ...
'    tripCount = 0;' ...
'    lockoutLatch = false;' ...
'    cbTripLatch = false;' ...
'end' ...
sprintf('RECV_N = %.17g;',recvN) ...
sprintf('LOCK_N = %.17g;',lockN) ...
sprintf('BREAKER_N = %.17g;',breakerN) ...
'gtTrip = gtTrip > 0.5;' ...
'relayHealthy = relayHealthy > 0.5;' ...
'resetCmd = resetCmd > 0.5;' ...
'cbClosed = cbClosed > 0.5;' ...
'if gtTrip' ...
'    tripCount = tripCount + 1;' ...
'else' ...
'    tripCount = 0;' ...
'end' ...
'recvState = gtTrip && relayHealthy && (tripCount > RECV_N);' ...
'if gtTrip && relayHealthy && (tripCount > LOCK_N)' ...
'    lockoutLatch = true;' ...
'end' ...
'if gtTrip && relayHealthy && (tripCount > BREAKER_N)' ...
'    cbTripLatch = true;' ...
'end' ...
'if resetCmd' ...
'    lockoutLatch = false;' ...
'    cbTripLatch = false;' ...
'end' ...
'lockoutState = lockoutLatch;' ...
'cbTripState = cbTripLatch;' ...
'if ~cbClosed && cbTripLatch' ...
'    cbTripState = true;' ...
'end' ...
'end'};
code=strjoin(lines,newline);
end

function code=buildStTripFunctionCode(breakerN)
lines={ ...
'function cbTripState = Logic(stTrip,resetCmd,cbClosed)' ...
'persistent tripCount cbTripLatch' ...
'if isempty(tripCount)' ...
'    tripCount = 0;' ...
'    cbTripLatch = false;' ...
'end' ...
sprintf('BREAKER_N = %.17g;',breakerN) ...
'stTrip = stTrip > 0.5;' ...
'resetCmd = resetCmd > 0.5;' ...
'cbClosed = cbClosed > 0.5;' ...
'if stTrip' ...
'    tripCount = tripCount + 1;' ...
'else' ...
'    tripCount = 0;' ...
'end' ...
'if stTrip && (tripCount > BREAKER_N)' ...
'    cbTripLatch = true;' ...
'end' ...
'if resetCmd' ...
'    cbTripLatch = false;' ...
'end' ...
'cbTripState = cbTripLatch;' ...
'if ~cbClosed && cbTripLatch' ...
'    cbTripState = true;' ...
'end' ...
'end'};
code=strjoin(lines,newline);
end

function code=buildBusFunctionCode(uvN,uvPickupKv)
lines={ ...
'function [uvA,uvB,tiePerm] = Logic(busAV,busBV,busANative,busBNative,busAFault,busBFault,autoTie,allowParallel)' ...
'persistent uvACount uvBCount' ...
'if isempty(uvACount)' ...
'    uvACount = 0;' ...
'    uvBCount = 0;' ...
'end' ...
sprintf('UV_N = %.17g;',uvN) ...
sprintf('UV_PICKUP = %.17g;',uvPickupKv) ...
'busANative = busANative > 0.5;' ...
'busBNative = busBNative > 0.5;' ...
'busAFault = busAFault > 0.5;' ...
'busBFault = busBFault > 0.5;' ...
'autoTie = autoTie > 0.5;' ...
'allowParallel = allowParallel > 0.5;' ...
'if busAV < UV_PICKUP' ...
'    uvACount = uvACount + 1;' ...
'else' ...
'    uvACount = 0;' ...
'end' ...
'if busBV < UV_PICKUP' ...
'    uvBCount = uvBCount + 1;' ...
'else' ...
'    uvBCount = 0;' ...
'end' ...
'uvA = uvACount > UV_N;' ...
'uvB = uvBCount > UV_N;' ...
'candidateA = uvA && (~busANative) && busBNative && (~busAFault);' ...
'candidateB = uvB && (~busBNative) && busANative && (~busBFault);' ...
'parallelRisk = busANative && busBNative && (~allowParallel);' ...
'tiePerm = autoTie && (candidateA || candidateB) && (~parallelRisk) && (~(busAFault && busBFault));' ...
'end'};
code=strjoin(lines,newline);
end

function code=buildStFunctionCode(stLowMw)
lines={ ...
'function stLow = Logic(stMw)' ...
sprintf('ST_LOW_MW = %.17g;',stLowMw) ...
'stLow = abs(stMw) < ST_LOW_MW;' ...
'end'};
code=strjoin(lines,newline);
end

function t=firstTrueTime(yout,index)
sig=yout.getElement(index).Values;
idx=find(logical(sig.Data),1,'first');
if isempty(idx), t=NaN; else, t=sig.Time(idx); end
end
